#107: product page gallery : update style fotorama from  Magento 2.1
SnowdogApps/magento2-theme-blank-sass pull request #108
Opened 2016-10-18 20:09 UTC by talalus

2016-10-20 08:46 UTC, Igloczek requested changes

2016-10-20 08:46 UTC, Igloczek commented on styles/blocks/_gallery.scss
> +// /**
Let's remove this useless Magento license comments ;)

2016-10-20 08:46 UTC, Igloczek commented on styles/blocks/_gallery.scss
>      display: none;
Can we move all styles below imports to partials too?

2016-10-20 08:46 UTC, Igloczek commented on styles/blocks/_gallery.scss
> -$fotorama-duration-time: 0.3s;
Would be great to move gallery styles to some module dir... But there is nothing like `MagentoGallery`, so probably best option will be `MagentoCatalog`.

2016-10-20 13:44 UTC, MrGekko commented on styles/blocks/_gallery.scss
> +    background-image: url('#{$baseDir}../images/loader-1.gif');
I was getting a 404 for loader-1.gif. After updating this line it worked. I think this should be:
background-image: url('#{$baseDir}images/loader-1.gif');

2016-10-20 13:49 UTC, Igloczek commented on styles/blocks/_gallery.scss
> +    background-image: url('#{$baseDir}../images/loader-1.gif');
`$baseDir` is just a `../`

2016-10-21 01:28 UTC, talalus commented on styles/blocks/_gallery.scss
>      display: none;
Sure, but I followed default Magento LESS structure so it'll be easy later to track changes and update blank theme and child themes

2016-10-24 22:12 UTC, Igloczek requested changes

2016-10-24 22:12 UTC, Igloczek commented on Magento_Catalog/styles/module/_gallery.scss
Can we move all of this code below to new partial or ideally few smaller partials (it's fu... 1000 lines of styles :O )?
This file should contain only imports.

2016-10-24 22:14 UTC, Igloczek commented on styles/blocks/_gallery.scss
>      display: none;
If we copy paste everything to new file, it will be easy to track this changes.

2016-10-28 14:56 UTC, Igloczek commented
Karol make all necessary changes in #110, so I merged this one instead of this changes.

2016-10-28 14:56 UTC, closed without merging