Patch button variables
SnowdogApps/magento2-theme-blank-sass pull request #151
Opened 2017-07-07 11:45 UTC by kweij

- Moved button variables to a variables file
- Added and used variables consistently for all types (default, secondary, small, large)
- Removed _lib-button-icon() in favor of lib-button-icon() with defaults

2017-07-07 11:48 UTC, Igloczek commented
Looks like a #142

2017-07-07 11:51 UTC, kweij commented
It does indeed - I was working on the same thing when I found out about #142. However, this one has all used settings available as variables. I find it a more thorough solution. Please consider it.

2017-08-24 16:03 UTC, Igloczek commented
@kweij Could you check what's wrong after the merge?

2017-09-21 09:54 UTC, Igloczek requested changes

2017-09-21 09:54 UTC, Igloczek commented on styles/vendor/magento-ui/variables/_buttons.scss
> +$button__cursor: pointer !default;
Could you align these variables vertically, same as they were aligned before?

2017-09-21 09:54 UTC, Igloczek commented on styles/blocks/_buttons.scss
> -}
Why is this code removed? It look like in the core - https://github.com/magento/magento2/blob/develop/app/design/frontend/Magento/blank/web/css/source/_buttons.less

2017-10-17 20:59 UTC, Igloczek commented
The content of this PR seems to be not valid anymore, b/c of the changes introduced in v1.0.0.

If you think it's still a case, please read the new contribution rules first.

2017-10-17 20:59 UTC, closed without merging